customCommands:
  - key: "C"
    command: "git czg ai -N=3"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
gui:
  mouseEvents: false
