# Display lazygit
bind -r g display-popup -d '#{pane_current_path}' -w85% -h85% -E lazygit

# Load an IDE layout
bind -r S new-window -n 'IDE' \; split-window -h -l 40% \; split-window -v -l 50%

# Run CLI in a separate session
# bind -r y run-shell '\
#   SESSION="codex-$(echo #{pane_current_path} | md5sum | cut -c1-8)"; \
#   tmux has-session -t "$SESSION" 2>/dev/null || \
#   tmux new-session -d -s "$SESSION" -c "#{pane_current_path}" "codex"; \
#   tmux display-popup -w85% -h85% -E "tmux attach-session -t $SESSION"'
